### ISSUE TITLE
reloadData removes all cells and doesn't add any back

### ISSUE THREAD

**Issue by shizam** [danielctull/DTGridView#2]
After the gridView is initialized, if you call reloadData it removes all the cells but doesn't add them back.  One specific suspicious spot is DTGridView ~line 384

```
if ([self.subviews count] > [self.gridCells count]) {
```

Problem is gridCells is a multidimensional array of the cells (row x column) where subviews is flat so that expression always evals to true.  The meat of the issue is in checkViews, thats where cells should be added (it appears) but aren't, they're only added on initialiseViews.

**Comment by danielctull** [comment]
Set needs display when -reloadData is called. Closed by 4536aaa34184b220f9b56deb5ac216ad4f411636.

**Comment by danielctull** [comment]
Hopefully this fix solves your problem, reopen this issue if it doesn't. :)

**Comment by shizam** [comment]
That did it, thanks!
