### ISSUE TITLE
DTInfiniteGridViewExampleViewController not infinite scroll

### ISSUE THREAD

**Issue by skoota** [danielctull/DTGridView#5]
Hi All,

When using the DTInfiniteGridViewExampleViewController in the demo project it seems that this does not demonstrate infinite horizontal scroll, as it stops horizontally scrolling after 10 cycles of the Red/Blue/Orange/Yellow views. Looking through the source code nothing jumps out as constraining the scroll to 10 cycles, and given that it should be infinite scroll I thought that it would just continue scrolling ad infinitum.

I am running the code in the iPhone Simulator using SDK 4.2. Thanks in advance for any assistance.

**Comment by danielctull** [comment]
Use -layoutSubviews to modify the position to make infinite scrolling work. Closed by 1d60af9affb677abdea3259896a6df915917009c.
